### ISSUE TITLE
Incorrect Output

### ISSUE THREAD

**Issue by chrisspen** [oriondevs/abc-transpose#2]
I'm not able to get this module to work as documented in the README.

If I do:

    const abc = require("abc-transpose");
    s="X:1\nT:Ode to Joy\nC:Ludwig van Beethoven\nM:C\nK:A\nL:1\n[K: clef=treble-8]\nc2 c2 d2 e2|e2 d2 c2 B2|A2 A2 B2 c2|c3 B B4|\nc2 c2 d2 e2|e2 d2 c2 B2|A2 A2 B2 c2|B3 A A4|\nB2 B2 c2 A2|B2 cd c2 A2|B2 cd c2 B2|A2 B2 E4|\nc2 c2 d2 e2|e2 d2 c2 B2|A2 A2 B2 c2|B3 A A4|]"
    console.log(abc.up(s))

It outputs:

    "K:BL\n"

When it would expect it to output:

    "X:1\nT:Ode to Joy\nC:Ludwig van Beethoven\nM:C\nK:B\nL:1/8\n[K: clef=treble-8]\nd2 d2 e2 f2|f2 e2 d2 c2|B2 B2 c2 d2|d3 c c4|\nd2 d2 e2 f2|f2 e2 d2 c2|B2 B2 c2 d2|c3 B B4|\nc2 c2 d2 B2|c2 de d2 B2|c2 de d2 c2|B2 c2 F4|\nd2 d2 e2 f2|f2 e2 d2 c2|B2 B2 c2 d2|c3 B B4|]"

What am I doing wrong?

**Comment by chrisspen** [comment]
I think I found the problem. It looks like your code only supports Windows-style newlines "\r\n", and I'm not on Windows, so it's treating my entire file as a single line.

I don't know if this is intentional or just a bug. I'd recommend supporting a more common "\n" newline. But it's easy enough for me to work around with a `replaceAll()`.

**Comment by lets00** [comment]
Hi @chrisspen. When I wrote this module, I used the Windows-style newlines. But I'll adapt it to use the Unix-style newlines format too.

**Comment by chrisspen** [comment]
Thanks. I appreciate it.

**Comment by lets00** [comment]
I've adapted to use Unix and Windows style-line.
