### ISSUE TITLE
Clef annotations corrupted

### ISSUE THREAD

**Issue by chrisspen** [oriondevs/abc-transpose#3]
This module breaks [clef annotations](http://abcnotation.com/wiki/abc:standard:v2.1#clefs_and_transposition).

For example, if a line is:

    K: A clef=treble-8

running `up()` will change it to:

     K: Bclef

when the `clef=<name>` part should be left untouched.

**Comment by lets00** [comment]
This is a bug, I'll investigate it.

**Comment by lets00** [comment]
I've fixed it. Please, check again with new version.

**Comment by chrisspen** [comment]
It's working great now. Thanks.
