### ISSUE TITLE
Decorations incorrectly transposed

### ISSUE THREAD

**Issue by chrisspen** [oriondevs/abc-transpose#4]
It looks like [!deorations!](http://abcnotation.com/wiki/abc:standard:v2.1#decorations) are being corrupted too.

For example, if I transpose this up:

    X:1
    L:1/8
    M:3/4
    K:G
    (3eBG (3gBG (3gBG & E,6 | (3gcA (3fcA (3fcA & A,6 | (3a^dA (3gdA (3fdA & B,6 | e2 !arpeggio![gbe']4 & E,6 |]

it becomes:

    X:1
    L:1/8
    M:3/4
    K:A
    (3fcA (3acA (3acA & F,6 | (3adB (3gdB (3gdB & B,6 | (3b^eB (3aeB (3geB & C6 | f2 !brpfaaio![ac'f']4 & F,6 |]

Note the letters in `!arpeggio!` have been transposed when they should have been left untouched.

**Comment by lets00** [comment]
I've fixed this bug. Please, check if decoration support is working properly.

**Comment by chrisspen** [comment]
Awesome. Thanks.
